// name=proto/ra.proto

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: proto/ra.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RAService_Request_FullMethodName = "/ra.RAService/Request"
	RAService_Reply_FullMethodName   = "/ra.RAService/Reply"
)

// RAServiceClient is the client API for RAService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RAServiceClient interface {
	Request(ctx context.Context, in *RequestMsg, opts ...grpc.CallOption) (*Ack, error)
	Reply(ctx context.Context, in *ReplyMsg, opts ...grpc.CallOption) (*Ack, error)
}

type rAServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRAServiceClient(cc grpc.ClientConnInterface) RAServiceClient {
	return &rAServiceClient{cc}
}

func (c *rAServiceClient) Request(ctx context.Context, in *RequestMsg, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, RAService_Request_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rAServiceClient) Reply(ctx context.Context, in *ReplyMsg, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, RAService_Reply_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RAServiceServer is the server API for RAService service.
// All implementations must embed UnimplementedRAServiceServer
// for forward compatibility.
type RAServiceServer interface {
	Request(context.Context, *RequestMsg) (*Ack, error)
	Reply(context.Context, *ReplyMsg) (*Ack, error)
	mustEmbedUnimplementedRAServiceServer()
}

// UnimplementedRAServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRAServiceServer struct{}

func (UnimplementedRAServiceServer) Request(context.Context, *RequestMsg) (*Ack, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Request not implemented")
}
func (UnimplementedRAServiceServer) Reply(context.Context, *ReplyMsg) (*Ack, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Reply not implemented")
}
func (UnimplementedRAServiceServer) mustEmbedUnimplementedRAServiceServer() {}
func (UnimplementedRAServiceServer) testEmbeddedByValue()                   {}

// UnsafeRAServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RAServiceServer will
// result in compilation errors.
type UnsafeRAServiceServer interface {
	mustEmbedUnimplementedRAServiceServer()
}

func RegisterRAServiceServer(s grpc.ServiceRegistrar, srv RAServiceServer) {
	// If the following call pancis, it indicates UnimplementedRAServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RAService_ServiceDesc, srv)
}

func _RAService_Request_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RAServiceServer).Request(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RAService_Request_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RAServiceServer).Request(ctx, req.(*RequestMsg))
	}
	return interceptor(ctx, in, info, handler)
}

func _RAService_Reply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReplyMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RAServiceServer).Reply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RAService_Reply_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RAServiceServer).Reply(ctx, req.(*ReplyMsg))
	}
	return interceptor(ctx, in, info, handler)
}

// RAService_ServiceDesc is the grpc.ServiceDesc for RAService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RAService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ra.RAService",
	HandlerType: (*RAServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Request",
			Handler:    _RAService_Request_Handler,
		},
		{
			MethodName: "Reply",
			Handler:    _RAService_Reply_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/ra.proto",
}
